version: '3'
services:
    db:
        image: 'mysql:8'
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel_mysql
            MYSQL_USER: mysql
            MYSQL_PASSWORD: secret
            TZ: 'Asia/Tokyo'
        ports:
            - '3306:3306'
        volumes:
            - './db-store:/var/lib/mysql'
            - './conf/my.cnf:/etc/mysql/conf.d/my.cnf'

